choco install firefox -y
choco install chocolatey-core.extension -y
choco install 7zip -y
choco install vlc -y
choco install git -y
choco install malwarebytes -y
choco install wireshark -y
choco install filezilla -y
choco install curl -y
choco install gimp -y
choco install spotify -y
choco install thunderbird -y
choco install nvidia-display-driver -y
choco install powertoys -y
choco install brave -y
choco install ffmpeg -y
choco install virtualbox -y
choco install wiztree -y
choco install ublockorigin-chrome -y
choco install qbittorrent -y
choco install tor-browser -y
choco install obs-studio -y
choco install bulk-crap-uninstaller -y
choco install discord -y
choco install sonarr -y
choco install radarr -y
choco install lidarr -y
choco install betterdiscord -y
choco install epicgameslauncher -y
choco install yt-dlp -y
choco install gallery-dl -y
choco install lghub -y
choco install libreoffice-fresh -y
choco install notion -y
choco install python -y
choco install rufus -y
choco install steam -y
choco install protonvpn -y
choco install protonmailbridge -y
choco install protondrive -y
choco install protonpass -y
choco install protonmail -y
choco install ubisoft-connect -y
choco install betterbird -y
choco install autodesk-fusion360 -y
choco install upscayl -y
choco install betaflight-configurator -y
choco install minecraft-launcher -y
choco install obsidian -y
choco install flameshot -y
choco install rockstar-launcher -y
choco install neovim -y
choco install fzf -y
